// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDizO1J0oPgo4JF9aYbO5vLep4pz2dS1L0',
    appId: '1:319288794259:web:d7d601b95f2dc0b36d0166',
    messagingSenderId: '319288794259',
    projectId: 'familydata-76fc6',
    authDomain: 'familydata-76fc6.firebaseapp.com',
    storageBucket: 'familydata-76fc6.appspot.com',
    measurementId: 'G-MFDRNL0R8E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdbMfC2mMPkSpTToN723Q7-UTZr2Jb6tY',
    appId: '1:319288794259:android:b2432e27ed6927f56d0166',
    messagingSenderId: '319288794259',
    projectId: 'familydata-76fc6',
    storageBucket: 'familydata-76fc6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaYdL_tFUi79iOfhy44f6ODZ27bbCqzjU',
    appId: '1:319288794259:ios:f5c8c7f6526076596d0166',
    messagingSenderId: '319288794259',
    projectId: 'familydata-76fc6',
    storageBucket: 'familydata-76fc6.appspot.com',
    iosBundleId: 'com.example.familyData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaYdL_tFUi79iOfhy44f6ODZ27bbCqzjU',
    appId: '1:319288794259:ios:e3643f3dfeddb3ce6d0166',
    messagingSenderId: '319288794259',
    projectId: 'familydata-76fc6',
    storageBucket: 'familydata-76fc6.appspot.com',
    iosBundleId: 'com.example.familyData.RunnerTests',
  );
}
